# fly.toml file generated for bandini on 2022-10-17T12:04:05+01:00

app = "bandini"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "flyio/hellofly:latest"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[servicesModel]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [servicesModel.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[servicesModel.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[servicesModel.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[servicesModel.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

    [[servicesModel]]
      internal_port = 5432 # Postgres instance
      protocol = "tcp"


    # Open port 10000 for plaintext connections.
    [[servicesModel.ports]]
      handlers = []
      port = 10000
